### PR TITLE
Hide the audit status filter on the report page

### PR DESCRIPTION
**Pull request by cbaines**
Also, don't filter by audit status at all on the report page.

### CODE REVIEW

**Comment by tuzz** [comment]
We could share the conditional between the controller and the view with:

```
# audits_controller.rb
helper_method :audit_status_filter_enabled?

def audit_status_filter_enabled?
  action_name != "report"
end
```

Then use that in both places.

**Comment by tuzz** [comment]
Tests are failing.

**Comment by cbaines** [comment]
Good idea about the controller method, I'll update.

**Comment by cbaines** [comment]
> Tests are failing and we really ought to test the audit status filter doesn't appear and isn't in effect on the report page (given this constituted a P1 – i.e. it's crucial this works as expected).

Finally I have written some passing tests. I got a bit muddled up with the test data, as I couldn't seem to get the organisation filter to contain anything, turns out I had the link type wrong.

**Pull request merged**
