### PR TITLE
Side-by-side content preview on audit pages

### PR DESCRIPTION
**Pull request by alecgibson**
This change merges in the changes made in these separate (feature branch) pull requests:

- https://github.com/alphagov/content-performance-manager/pull/414
- https://github.com/alphagov/content-performance-manager/pull/415
- https://github.com/alphagov/content-performance-manager/pull/419

Please see separate PRs for further context.

### CODE REVIEW

**Comment by pmanrubia** [comment]
@alecgibson The build on this PR seems to be broken:
```
[ger_feature_content-preview-UQNHC6ZVNLSACJR4VT6PPE4VXR7ARH5FFIWTYJSEFDSGJAM2MYYA] Running shell script
+ docker build -t govuk/content-performance-manager:feature/content-preview .
invalid argument "govuk/content-performance-manager:feature/content-preview" for t: invalid reference format
See 'docker build --help'.
```

**Comment by alecgibson** [comment]
@pmanrubia I'm looking into it - it's because the branch name has a slash in it, which is upsetting the Docker step in our build chain. Getting a fix ready for puppet.

**Comment by alecgibson** [comment]
Greenifying the build is blocked on this PR: https://github.com/alphagov/govuk-puppet/pull/6905

**Comment by alecgibson** [comment]
Review app here: https://cpm-prototype-422.herokuapp.com

**Comment by alecgibson** [comment]
@pmanrubia the build is now green - can you please review the merge?

**Pull request merged**
