### PR TITLE
Remove audit tool code from cpm

### PR DESCRIPTION
**Pull request by KyleMacPherson**
Remove the Audit Tool code from the Content Performance Manager so that the devs on the team are able to iterate the codebase for the Content Performance Manager without the burden of maintaining the legacy code for the Audit Tool.

### CODE REVIEW

**Comment by pmanrubia** [comment]
@KyleMacPherson could you please have a look at this as well:

1. `app/forms/taxonomy_todo_form.rb`
2.  `ItemDecorator#proxy_url`,`ItemDecorator#auditor`,`ItemDecorator#auditor_org`
3.  `Content` scope.
4.  `FindOrganisationUsers`
5.  Audit views in `app/views/audits`
6.  Some helpers that feed those views
7.  `lib/proxies`
8.  `lib/markdown_renderer`
9.  `tasks/term_generation`

**Comment by KyleMacPherson** [comment]
@pmanrubia have removed everything described in your comment apart from the content scope. I started it but it affects so many files I would prefer to put it in a seperate PR if that is ok with you?

**Comment by KyleMacPherson** [comment]
Ah ok @pmanrubia. Will try to get it all in this PR then!

**Comment by MatMoore** [comment]
@KyleMacPherson, me and @chao-xian have rebased this PR onto the latest master. Hopefully that hasn't changed anything but let us know if anything looks wrong.

We're planning to add an additional commit to this branch to redirect /audits to the audit tool before we merge this.

**Comment by chao-xian** [comment]
[(1) Clean up CPM (dependent on card 61)](https://trello.com/c/W1g3v67J/23-1-clean-up-cpm-dependent-on-card-61)

**Pull request merged**
